let firstText = [
`
Lorem ipsum dolor sit am<i>et, consectetur adipiscing elit, sed do eiusmod tempor incididunt u</i>t labore et dolore magna aliqua. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Nibh mauris cursus mattis molestie a. Porttitor massa id neque aliquam vestibulum. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Elementum integer enim neque volutpat. In cursus turpis massa tincidunt dui ut. Lacinia quis vel eros donec ac odio tempor orci. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Ullamcorper morbi tincidunt ornare massa. Diam quis enim lobortis scelerisque fermentum dui faucibus. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Nascetur ridiculus mus mauris vitae ultricies leo integer. Eget duis at tellus at urna condimentum mattis. Tincidunt nunc pulvinar sapien et.
`,
`
Habitant morbi tristique senectus et netus et malesuada fames ac. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Maecenas volutpat blandit aliquam etiam. Lectus proin nibh nisl condimentum id venenatis a. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Mi proin sed libero enim sed. Vitae et leo duis ut diam quam. Enim nulla aliquet porttitor lacus luctus accumsan tortor. In aliquam sem fringilla ut. Platea dictumst quisque sagittis purus sit. Nunc id cursus metus aliquam. Pellentesque habitant morbi tristique senectus et. Dolor sit amet consectetur adipiscing elit. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Tincidunt arcu non sodales neque. Mollis aliquam ut porttitor leo.
`,
`
Vitae semper quis lectus nulla at volutpat diam. Id interdum velit laoreet id donec ultrices tincidunt. Nunc vel risus commodo viverra maecenas accumsan. Elit pellentesque habitant morbi tristique senectus et. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Dolor morbi non arcu risus quis varius quam quisque. Venenatis cras sed felis eget velit. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Volutpat commodo sed egestas egestas fringilla. Venenatis lectus magna fringilla urna.
`,
`
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ull
`,
`
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ip
`
];

let secondText = [
`
Proin libero nunc consequat interdum varius sit amet mattis vulputate. Congue quisque egestas diam in arcu. Nisi scelerisque eu ultrices vitae. Facilisis mauris sit amet massa vitae tortor. Quis varius quam quisque id diam vel quam elementum. Leo urna molestie at elementum. Mauris a diam maecenas sed. Egestas congue quisque egestas diam in arcu. Eget felis eget nunc lobortis mattis aliquam. Nulla malesuada pellentesque elit eget gravida cum sociis. Eros in cursus turpis massa tincidunt dui. Non diam phasellus vestibulum lorem. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas.
`,
`
Incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit am
`,
`
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis. Amet mattis vulputate enim nulla aliquet porttitor. Nulla facilisi cras fermentum odio eu. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. At auctor urna nunc id cursus metus. Maecenas sed enim ut sem viverra aliquet. Proin sed libero enim sed faucibus turpis. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Magna sit amet purus gravida. Vitae aliquet nec ullamcorper sit amet. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum.
`,
`
Arcu non sodales <b>neque sodales. Vitae proin sagittis</b> nisl rhoncus mattis rhoncus urna neque. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Eu augue ut lectus arcu bibendum. Tincidunt lobortis feugiat vivamus at augue eget. Fringilla urna porttitor rhoncus dolor purus. Ipsum consequat nisl vel pretium lectus quam id leo. Magna sit amet purus gravida quis blandit turpis cursus. In iaculis nunc sed augue lacus viverra. Imperdiet dui accumsan sit amet nulla.
`,
`
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id porta nibh venenatis cras sed felis. Amet mattis vulputate enim nulla aliquet porttitor. Nulla facilisi cras fermentum odio eu. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. At auctor urna nunc id cursus metus. Maecenas sed enim ut sem viverra aliquet. Proin sed libero enim sed faucibus turpis. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Magna sit amet purus gravida. Vitae aliquet nec ullamcorper sit amet. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum.
`
];

let thirdText = [
`
Arcu non sodales <b>neque sodales. Vitae proin sagittis</b> nisl rhoncus mattis rhoncus urna neque. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Eu augue ut lectus arcu bibendum. Tincidunt lobortis feugiat vivamus at augue eget. Fringilla urna porttitor rhoncus dolor purus. Ipsum consequat nisl vel pretium lectus quam id leo. Magna sit amet purus gravida quis blandit turpis cursus. In iaculis nunc sed augue lacus viverra. Imperdiet dui accumsan sit amet nulla.
`,
`
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum dolore eu fugiat nullapariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum. Lorem ip
`,
`
Vitae semper quis lectus nulla at volutpat diam. Id interdum velit laoreet id donec ultrices tincidunt. Nunc vel risus commodo viverra maecenas accumsan. Elit pellentesque habitant morbi tristique senectus et. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Dolor morbi non arcu risus quis varius quam quisque. Venenatis cras sed felis eget velit. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Volutpat commodo sed egestas egestas fringilla. Venenatis lectus magna fringilla urna.
`,
`
Habitant morbi tristique senectus et netus et malesuada fames ac. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Maecenas volutpat blandit aliquam etiam. Lectus proin nibh nisl condimentum id venenatis a. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Mi proin sed libero enim sed. Vitae et leo duis ut diam quam. Enim nulla aliquet porttitor lacus luctus accumsan tortor. In aliquam sem fringilla ut. Platea dictumst quisque sagittis purus sit. Nunc id cursus metus aliquam. Pellentesque habitant morbi tristique senectus et. Dolor sit amet consectetur adipiscing elit. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Tincidunt arcu non sodales neque. Mollis aliquam ut porttitor leo.
`,
`
Lorem ipsum dolor sit am<i>et, consectetur adipiscing elit, sed do eiusmod tempor incididunt u</i>t labore et dolore magna aliqua. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Nibh mauris cursus mattis molestie a. Porttitor massa id neque aliquam vestibulum. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Elementum integer enim neque volutpat. In cursus turpis massa tincidunt dui ut. Lacinia quis vel eros donec ac odio tempor orci. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Ullamcorper morbi tincidunt ornare massa. Diam quis enim lobortis scelerisque fermentum dui faucibus. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Nascetur ridiculus mus mauris vitae ultricies leo integer. Eget duis at tellus at urna condimentum mattis. Tincidunt nunc pulvinar sapien et.
`
];
